config/routes.rb
Rails.application.routes.draw do
  devise_for :job_masters

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

	root 'info#index'

	get '/crews/:day/(:color)', to: 'info#by_day_and_color'
	get '/days/:year/:month/:day', to: 'info#by_date'

end

app/models/crew.rb
class Crew < ActiveRecord::Base
	# Attributes:
	# color:string
	# day:string
	# crew_head:string
	
	has_many :students, dependent: :destroy
	validates :color, :presence => true
	validates :day, :presence => true

	Color_Hash = { 'purple' => [:red, :blue], 'orange' => [:red, :yellow], 'green' => [:yellow, :blue], 'rainbow' => [:red, :yellow, :blue] }

	def new
	end

	def self.current
		# return the current crews as a ActiveRecord query
		curweek = Week.current
		if curweek
			return Crew.by_day_and_color(Time.now.strftime("%A").downcase, curweek.color)
		else
			return nil
		end
	end

	def self.by_date(year, month, day)
		curweek = Week.by_date(year, month, day)
		if curweek
			return Crew.by_day_and_color(Time.mktime(year, month, day).strftime("%A").downcase, curweek.color)
		else
			return nil
		end
	end

	def self.by_day_and_color(day, color)
		crew_map = Hash.new
		[ :recess, :setup ].each.with_index do |item, i|
			crew_map[item] = Crew.find_by(day: day, color: item.to_s)
		end
		Color_Hash[color].each.with_index do |col, i|
			crew_map[:"lunch#{i}"] = Crew.find_by(day: day, color: col.to_s)
		end
		crew_map
	end

	def color_enum
		['red', 'blue', 'yellow', 'setup', 'recess']
	end

	def day_enum
		['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
	end

end

app/models/job_master.rb
class JobMaster < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :rememberable, :trackable, :validatable
end

app/models/student.rb
class Student < ActiveRecord::Base
	# Attributes:
	# name:string

	belongs_to :crew

	def new
	end

end

app/models/week.rb
class Week < ActiveRecord::Base
	# Attributes:
	# color:string
	# start_day:date
	belongs_to :week_type
	validates :color, :presence => true
	validates :start_day, :presence => true

	def new
	end

	def color_enum
		["rainbow", "purple", "orange", "green"]
	end

	def self.current
		# return the current week based on the time this was called
		now = Time.now
		Week.find_by(start_day: now.midnight - ((now.wday - 1) * 60 * 60 * 24))
	end

	def self.by_date(year, month, day)
		now = Time.mktime(year, month, day)
		Week.find_by(start_day: now.midnight - ((now.wday - 1) * 60 * 60 * 24))
	end
end

app/models/week_type.rb
class WeekType < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
	def new
		@crew = Crew.new
	end

	def create
		@crew = Crew.new crew_params

		@crew.create_crew_head crew_head_params

		params[:crew][:students][:names].split(", ").each do |student|
			@crew.students.create name: student
		end

		@crew.save

		redirect_to crews_path
	end

	def index
		@crews = Crew.all
	end

	def update
		@crew = Crew.find params[:id]
		@crew.update crew_params

		@crew.crew_head.update crew_head_params
		puts @crew

		if @crew.students.map{ |s| s.name }.join(", ") != params[:crew][:students][:names]
			@crew.students.each { |s| s.destroy }

			params[:crew][:students][:names].split(", ").each do |student|
				@crew.students.create name: student
			end
		end

		@crew.save

		redirect_to crews_path
	end

	def destroy
		@crew = Crew.find params[:id]

		@crew.destroy
		redirect_to crews_path
	end

	def edit
		@crew = Crew.find params[:id]
	end

	private
	def crew_params
		params.require(:crew).permit :color, :day
	end

	def crew_head_params
		params.require(:crew).require(:crew_head).permit(:name)
	end
end

app/controllers/info_controller.rb
class InfoController < ApplicationController
	def index
		@week = Week.current
    @crews_json = { :day => Time.now.strftime("%A").downcase, :color => @week.color }
	end

	def by_day_and_color
		if params[:color]
			@crews = Crew.by_day_and_color(params[:day], params[:color])
			@color = params[:color].capitalize
		else
			@crews = Crew.by_day_and_color(params[:day], 'rainbow')
			@color = 'Rainbow'
		end
		@day = params[:day].capitalize
		render json: { :crews => crews_to_hash(@crews) }
	end

	def crews_to_hash(crews)
		json = Hash.new
		@crews.each do |col, c|
			json[col] = { :day => c.day, :color => c.color, :crew_head => c.crew_head, :students => c.students.map{|s| s.name } }
		end
		json
	end

	def week_to_hash(week)
		{ :start_date => week.start_day.strftime("%Y-%m-%d"), :color => week.color}
	end

	def to_hash(week, crews)
		{ :crews => crews_to_hash(crews), :week => week_to_hash(week) }
	end

	def by_date
		@week = Week.by_date(params[:year], params[:month], params[:day])
		@crews = Crew.by_date(params[:year], params[:month], params[:day])
		render json: to_hash(@week, @crew)
	end
end

app/controllers/weeks_controller.rb
class WeeksController < ApplicationController
	def new
		@week = Week.new
	end

	def create
		#render plain: params[:week].inspect
		@week = Week.new week_params
		
		@week.save
		redirect_to new_week_path
	end

	def index
		@weeks = Week.all
	end

	def show
		@week = Week.find params[:id]
	end

	def edit
		@week = Week.find params[:id]
	end

	def update
		@week = Week.find params[:id]
		@week.update week_params
		redirect_to weeks_path
	end

	def destroy
		@week = Week.find params[:id]

		@week.destroy
		redirect_to weeks_path
	end

	private
		def week_params
			params.require(:week).permit(:color, :start_day)
		end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/crews_helper.rb
module CrewsHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/crews/_form.html.erb
<%= form_for @crew do |f| %>
	<p>
		<%= f.label :color %>:
		<%= f.select :color, [["red", "red"], ["yellow", "yellow"], ["blue", "blue"], ["setup", "setup"], ["recess", "recess"]] %>
	</p>

	<p>
		<%= f.label :day %>:
		<%= f.text_field :day %>
	</p>

	<p>
		Crew Head:
		<%= fields_for "crew[crew_head]", @crew.crew_head do |head_f| %>
			<%= head_f.text_field :name %>
		<% end %>
	</p>

	<p>
		Students:<br />
		<textarea id="crew_students_names" name="crew[students][names]"><%= @crew.students.map{|s| s.name }.join ", " %></textarea>
	</p>
	
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/crews/edit.html.erb
<h1>Update Crew</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/crews/index.html.erb
<h1>Listing Crews</h1>

<%= link_to 'New Crew', new_crew_path %>

<ul>
	<% @crews.each do |crew| %>
		<li> Day: <%= crew.day %>, Color: <%= crew.color %>
		<ul>
			<li>Crew Head: <%= crew.crew_head.name %></li>
			<% crew.students.each do |student| %>
				<li> <%= student.name %> </li>
			<% end %>
			<li> <%= link_to 'Edit', edit_crew_path(crew) %> </li>
			<li> <%= link_to 'Destroy', crew_path(crew), method: :delete, data: { confirm: 'Are you sure?' } %></li>
		</ul>
		</li>
	<% end %>
</ul>

app/views/crews/new.html.erb
<h1>New Crew</h1>

<%= render 'form' %>

app/views/info/_crews.html.erb
<div class="row">
	<div class="col-md-3 col-md-offset-3">
		<h3>Recess Cleanup</h3>
		<% @crews[:recess].students.each do |s| %>
			<%= s.name %><br />
		<% end %>
	</div>
	<div class="col-md-3">
		<h3>Lunch Setup</h3>
		<% @crews[:setup].students.each do |s| %>
			<%= s.name %><br />
		<% end %>
	</div>
</div>
<div class="row">
	<div class="col-md-3 col-md-offset-3">
		<h3><%= @crews[:lunch0].color.capitalize %> Lunch Crew</h3>
		<p><strong>Crew Head: </strong> <%= @crews[:lunch0].crew_head %></p>
		<p>
			<% @crews[:lunch0].students.sort{|a, b| a.name <=> b.name }.each do |s| %>
				<% if s.name != @crews[:lunch0].crew_head %>
					<%= s.name %> </br>
		<% end %>
	<% end %>
		</p>
	</div>
	<div class="col-md-3">
		<h3><%= @crews[:lunch1].color.capitalize %> Lunch Crew</h3>
		<p><strong>Crew Head: </strong> <%= @crews[:lunch1].crew_head %></p>
		<p>
			<% @crews[:lunch1].students.sort{|a, b| a.name <=> b.name }.each do |s| %>
				<% if s.name != @crews[:lunch1].crew_head %>
					<%= s.name %> </br>
		<% end %>
	<% end %>
		</p>
	</div>
</div>
<div class="row">
	<div class="col-md-3 col-md-offset-3">
		<% if @crews[:lunch2] %>
			<h3><%= @crews[:lunch2].color.capitalize %> Lunch Crew</h3>
			<p><strong>Crew Head: </strong> <%= @crews[:lunch2].crew_head %></p>
			<p>
				<% @crews[:lunch2].students.sort{|a, b| a.name <=> b.name }.each do |s| %>
					<% if s.name != @crews[:lunch2].crew_head %>
						<%= s.name %> </br>
					<% end %>
				<% end %>
			</p>
		<% end %>
	</div>
</div>

app/views/info/_mermaid.html.erb
<div class="row">
	<div class="col-md-2 col-md-offset-3">
		<img src="/mermaid.gif" alt="Our Beloved Mermaid" title="Our Beloved Mermaid"/>
	</div>
	<div class="col-md-4">
		<h1><%= title %></h1>
	</div>
</div>

app/views/info/by_day_and_color.html.erb
<%= render :partial => 'mermaid', :locals => { :title => "Jobs on #{@day} for a #{@color} week"} %>
<% if not @crews.nil? %>
	<%= render 'crews' %>
<% else %>
	<div class="col-md-6 col-md-offset-3">
		<h1>No Crews found for today</h1>
	</div>
<% end %>

app/views/info/index.html.erb
<div class="container">
<%= render :partial => 'mermaid', :locals => { :title => "Jobs Today"} %>
<%= react_component('CrewsDisplay', @crews_json) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CommschoolJobs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/weeks/_form.html.erb
<%= form_for @week do |f| %>
	<p>
		<%= f.label :color %><br />
		<%= f.text_field :color %>
	</p>
	<p>
		<%= f.label :start_day %><br />
		<%= f.date_field :start_day %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/weeks/edit.html.erb
<h1>Edit Week</h1>

<%= render 'form' %>

<%= link_to 'Back', weeks_path %>

app/views/weeks/index.html.erb
<h1>Listing Weeks</h1>

<table class="table">
	<tr>
		<th>Start</th>
		<th>Color</th>
	</tr>
	<% @weeks.each do |week| %>
		<tr>
			<td><%= week.start_day %></td>
			<td><%= week.color %></td>
			<td><%= link_to 'Edit', edit_week_path(week) %></td>
			<td><%= link_to 'Destroy', week_path(week), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>

<%= link_to 'New Week', new_week_path %>

app/views/weeks/new.html.erb
<%= form_for :week, url: weeks_path do |f| %>
	<p>
		<%= f.label :color %><br />
		<%= f.text_field :color %>
	</p>
	<p>
		<%= f.label :start_day %><br />
		<%= f.date_field :start_day %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>